[package]
name = "mg-pocket-launcher"
version = "1.1.0"
description = "M&G Pocket Launcher"
authors = ["M&G Pocket"]
license = "MIT"
repository = "https://github.com/jvitorn/meg-pocket"
edition = "2021"

[lib]
name = "mg_pocket_launcher_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
getrandom = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tauri = { version = "2", features = [] }
